"""Ensure barcode field exists

Revision ID: 86da9be7fcab
Revises: 2ba92580fcc5
Create Date: 2026-02-04 22:33:11.117518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86da9be7fcab'
down_revision = '2ba92580fcc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
