"""Add orders and competitor pricing tables

Revision ID: 2ba92580fcc5
Revises: d9dd23e7a3a5
Create Date: 2026-02-04 22:30:35.314297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba92580fcc5'
down_revision = 'd9dd23e7a3a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
