"""Add barcode field to inventory

Revision ID: d9dd23e7a3a5
Revises: 00a8455edbc4
Create Date: 2026-02-04 22:27:33.812726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dd23e7a3a5'
down_revision = '00a8455edbc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_inventory_barcode'), 'inventory', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_barcode'), table_name='inventory')
    op.drop_column('inventory', 'barcode')
    # ### end Alembic commands ###
